# Generated by Django 5.1.2 on 2024-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.CharField(max_length=50),
        ),
    ]
