# Generated by Django 5.1.2 on 2024-12-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumsApp', '0002_alter_album_banda'),
        ('bandasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandasApp.banda'),
        ),
    ]
