# Generated by Django 5.1.2 on 2024-12-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada', models.FileField(upload_to='albums')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandasApp.banda')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
