# Generated by Django 5.1.2 on 2024-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
